# Generated by Django 6.0.2 on 2026-02-19 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchofficial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_players', to='matches.match'),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player'),
        ),
        migrations.AddField(
            model_name='matchstaff',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='matches.match'),
        ),
        migrations.AddField(
            model_name='matchstaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('tournament', 'match_number')},
        ),
        migrations.AlterUniqueTogether(
            name='matchofficial',
            unique_together={('match', 'user', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='matchplayer',
            unique_together={('match', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='matchstaff',
            unique_together={('match', 'user', 'role')},
        ),
    ]
