# Generated by Django 6.0.2 on 2026-02-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_ended_at_match_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20),
        ),
    ]
