# Generated by Django 6.0.2 on 2026-02-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_matchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round_number',
            field=models.PositiveIntegerField(blank=True, help_text='Round number (for knockout stages)', null=True),
        ),
    ]
