# Generated by Django 6.0.2 on 2026-02-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='age_group',
            field=models.CharField(blank=True, choices=[('U14', 'Under 14'), ('U17', 'Under 17'), ('U19', 'Under 19'), ('OPEN', 'Open')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='court_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
