# Generated by Django 6.0.2 on 2026-02-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_age_group_match_court_no_match_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchofficial',
            name='role',
            field=models.CharField(choices=[('UMPIRE', 'Umpire'), ('REFEREE', 'Referee'), ('SCORER', 'Scorer'), ('TIME_KEEPER', 'Time Keeper')], max_length=20),
        ),
    ]
