# Generated by Django 6.0.2 on 2026-02-28 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-total_points', 'name']},
        ),
        migrations.AddField(
            model_name='team',
            name='captain_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='coach_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='team',
            name='coach_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
        migrations.AddField(
            model_name='team',
            name='matches_drawn',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='matches_lost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='matches_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='matches_won',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DISQUALIFIED', 'Disqualified'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['tournament', 'status'], name='teams_team_tournam_442916_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['total_points'], name='teams_team_total_p_b41522_idx'),
        ),
    ]
