# Generated by Django 6.0.2 on 2026-02-16 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='short_code',
        ),
    ]
