# Generated by Django 6.0.2 on 2026-02-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('official', 'Official'), ('scorer', 'Scorer'), ('organizer', 'Organizer')], default='user', max_length=20),
        ),
    ]
