# Generated by Django 6.0.2 on 2026-02-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_city_user_gender_user_phone_number_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('REFEREE', 'Referee'), ('UMPIRE', 'Umpire'), ('SCORER', 'Scorer'), ('COACH', 'Coach'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20),
        ),
    ]
