# Generated by Django 6.0.2 on 2026-02-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('MEN', 'Men'), ('WOMEN', 'Women')], max_length=10)),
                ('age_group', models.CharField(choices=[('U14', 'Under 14'), ('U16', 'Under 16'), ('U18', 'Under 18'), ('OPEN', 'Open')], default='OPEN', max_length=10)),
                ('format_type', models.CharField(choices=[('LEAGUE', 'League'), ('KNOCKOUT', 'Knockout'), ('ROUND_ROBIN', 'Round Robin')], default='LEAGUE', max_length=20)),
                ('max_time_per_turn', models.PositiveIntegerField(default=30, help_text='Time per turn in seconds')),
                ('max_teams', models.PositiveIntegerField(default=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('organizer', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='UPCOMING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
