# Generated by Django 6.0.1 on 2026-01-26 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TOUCH', 'Touch'), ('OUT', 'Out'), ('BONUS', 'Bonus'), ('FOUL', 'Foul')], max_length=20)),
                ('points', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attacking_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacking_events', to='teams.team')),
                ('defending_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defending_events', to='teams.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='matches.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.player')),
            ],
        ),
    ]
