# Generated by Django 6.0.2 on 2026-02-19 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0002_initial'),
        ('players', '0001_initial'),
        ('scoring', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreauditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='attacking_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacking_events', to='teams.team'),
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='defending_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defending_events', to='teams.team'),
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='matches.match'),
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.player'),
        ),
    ]
