# Generated by Django 6.0.2 on 2026-02-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_scoreauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreevent',
            name='event_type',
            field=models.CharField(choices=[('TOUCH', 'Touch'), ('OUT', 'Out'), ('BONUS', 'Bonus'), ('ALL_OUT', 'All Out'), ('FOUL', 'Foul')], max_length=20),
        ),
    ]
